import { useState } from 'react';
import { FlareEntry } from '@/types/flare';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { format } from 'date-fns';
import { 
  FileText, 
  Download, 
  Share2, 
  Building2, 
  ClipboardCheck,
  ArrowRight,
  CheckCircle2,
  Loader2,
  Copy,
  ExternalLink
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { useToast } from '@/hooks/use-toast';

interface ClinicalRecordGeneratorProps {
  entry: FlareEntry | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export const ClinicalRecordGenerator = ({ entry, open, onOpenChange }: ClinicalRecordGeneratorProps) => {
  const { toast } = useToast();
  const [generating, setGenerating] = useState(false);
  const [generatedRecord, setGeneratedRecord] = useState<string | null>(null);
  const [format_, setFormat] = useState<'narrative' | 'fhir' | 'hl7'>('narrative');

  const generateRecord = async () => {
    if (!entry) return;
    
    setGenerating(true);
    
    // Simulate generation (in production, this would call an AI endpoint)
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    const record = generateClinicalNarrative(entry);
    setGeneratedRecord(record);
    setGenerating(false);
  };

  const generateClinicalNarrative = (entry: FlareEntry): string => {
    const date = format(entry.timestamp, 'MMMM d, yyyy');
    const time = format(entry.timestamp, 'h:mm a');
    
    let narrative = `PATIENT-GENERATED CLINICAL EVENT RECORD\n`;
    narrative += `Date: ${date} at ${time}\n`;
    narrative += `Record Type: Patient-Reported Flare Event\n`;
    narrative += `─────────────────────────────────────────\n\n`;
    
    narrative += `CHIEF COMPLAINT:\n`;
    narrative += `Patient reports a ${entry.severity || 'unspecified'} flare episode.\n\n`;
    
    if (entry.symptoms && entry.symptoms.length > 0) {
      narrative += `SYMPTOMS REPORTED:\n`;
      entry.symptoms.forEach(s => {
        narrative += `• ${s}\n`;
      });
      narrative += `\n`;
    }
    
    if (entry.triggers && entry.triggers.length > 0) {
      narrative += `IDENTIFIED TRIGGERS:\n`;
      entry.triggers.forEach(t => {
        narrative += `• ${t}\n`;
      });
      narrative += `\n`;
    }
    
    if (entry.environmentalData) {
      narrative += `ENVIRONMENTAL CONTEXT:\n`;
      if (entry.environmentalData.location?.city) {
        narrative += `• Location: ${entry.environmentalData.location.city}\n`;
      }
      if (entry.environmentalData.weather) {
        const w = entry.environmentalData.weather;
        if (w.temperature) narrative += `• Temperature: ${w.temperature}°F\n`;
        if (w.humidity) narrative += `• Humidity: ${w.humidity}%\n`;
        if (w.condition) narrative += `• Conditions: ${w.condition}\n`;
        if (w.pressure) narrative += `• Barometric Pressure: ${w.pressure} inHg\n`;
      }
      narrative += `\n`;
    }
    
    if (entry.physiologicalData) {
      narrative += `PHYSIOLOGICAL METRICS (Wearable Device):\n`;
      const p = entry.physiologicalData;
      if (p.heartRate) narrative += `• Heart Rate: ${p.heartRate} bpm\n`;
      if (p.sleepHours) narrative += `• Sleep Duration: ${p.sleepHours} hours\n`;
      if (p.sleepQuality) narrative += `• Sleep Quality: ${p.sleepQuality}\n`;
      if (p.steps) narrative += `• Daily Steps: ${p.steps.toLocaleString()}\n`;
      if (p.stressLevel) narrative += `• Stress Level: ${p.stressLevel}/10\n`;
      narrative += `\n`;
    }
    
    if (entry.note) {
      narrative += `PATIENT NOTES:\n`;
      narrative += `"${entry.note}"\n\n`;
    }
    
    narrative += `─────────────────────────────────────────\n`;
    narrative += `This record was generated by Jvala from patient-reported data.\n`;
    narrative += `For clinical use, please verify with the patient.\n`;
    narrative += `Generated: ${format(new Date(), 'PPpp')}\n`;
    
    return narrative;
  };

  const copyToClipboard = () => {
    if (generatedRecord) {
      navigator.clipboard.writeText(generatedRecord);
      toast({ title: "Copied to clipboard" });
    }
  };

  if (!entry) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" />
            Generate Clinical Record
          </DialogTitle>
          <DialogDescription>
            Transform this flare event into an EHR-compatible clinical record
          </DialogDescription>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto space-y-4 py-4">
          {/* Entry Summary */}
          <Card className="p-4 bg-muted/30">
            <div className="flex items-start gap-3">
              <div className={cn(
                "w-10 h-10 rounded-lg flex items-center justify-center",
                entry.severity === 'severe' ? 'bg-severity-severe' :
                entry.severity === 'moderate' ? 'bg-severity-moderate' :
                'bg-severity-mild'
              )}>
                <span className="text-white text-lg">⚡</span>
              </div>
              <div className="flex-1">
                <p className="text-sm font-medium">
                  {entry.severity?.charAt(0).toUpperCase()}{entry.severity?.slice(1)} Flare Event
                </p>
                <p className="text-xs text-muted-foreground">
                  {format(entry.timestamp, 'EEEE, MMMM d, yyyy • h:mm a')}
                </p>
                <div className="flex flex-wrap gap-1 mt-2">
                  {entry.symptoms?.slice(0, 3).map((s, i) => (
                    <Badge key={i} variant="outline" className="text-[10px]">{s}</Badge>
                  ))}
                  {entry.environmentalData && (
                    <Badge variant="secondary" className="text-[10px]">Environmental Data</Badge>
                  )}
                  {entry.physiologicalData && (
                    <Badge variant="secondary" className="text-[10px]">Wearable Data</Badge>
                  )}
                </div>
              </div>
            </div>
          </Card>

          {/* Format Selection */}
          <div className="space-y-3">
            <h4 className="text-sm font-medium">Output Format</h4>
            <Tabs value={format_} onValueChange={(v) => setFormat(v as any)}>
              <TabsList className="grid grid-cols-3 w-full">
                <TabsTrigger value="narrative" className="text-xs gap-1.5">
                  <FileText className="w-3.5 h-3.5" />
                  Narrative
                </TabsTrigger>
                <TabsTrigger value="fhir" className="text-xs gap-1.5">
                  <ClipboardCheck className="w-3.5 h-3.5" />
                  FHIR R4
                </TabsTrigger>
                <TabsTrigger value="hl7" className="text-xs gap-1.5">
                  <Building2 className="w-3.5 h-3.5" />
                  HL7
                </TabsTrigger>
              </TabsList>
            </Tabs>
          </div>

          {/* Generate Button */}
          {!generatedRecord && (
            <Button 
              onClick={generateRecord} 
              disabled={generating}
              className="w-full gap-2"
            >
              {generating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  Generate Clinical Record
                  <ArrowRight className="w-4 h-4" />
                </>
              )}
            </Button>
          )}

          {/* Generated Record */}
          {generatedRecord && (
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-severity-none" />
                  <span className="text-sm font-medium">Record Generated</span>
                </div>
                <div className="flex gap-1">
                  <Button variant="ghost" size="sm" onClick={copyToClipboard} className="gap-1.5">
                    <Copy className="w-3.5 h-3.5" />
                    Copy
                  </Button>
                  <Button variant="ghost" size="sm" className="gap-1.5">
                    <Download className="w-3.5 h-3.5" />
                    Download
                  </Button>
                </div>
              </div>
              
              <Card className="p-4 bg-muted/30 font-mono text-xs">
                <pre className="whitespace-pre-wrap text-foreground/90">{generatedRecord}</pre>
              </Card>
            </div>
          )}

          {/* Integration Options */}
          {generatedRecord && (
            <div className="space-y-3">
              <h4 className="text-sm font-medium">Integration Options</h4>
              <div className="grid grid-cols-2 gap-2">
                <Button variant="outline" className="h-auto py-3 flex-col items-start gap-1">
                  <div className="flex items-center gap-2 w-full">
                    <Building2 className="w-4 h-4 text-primary" />
                    <span className="text-xs font-medium">Send to EHR</span>
                    <ExternalLink className="w-3 h-3 ml-auto text-muted-foreground" />
                  </div>
                  <span className="text-[10px] text-muted-foreground">Epic, Cerner, Athena</span>
                </Button>
                <Button variant="outline" className="h-auto py-3 flex-col items-start gap-1">
                  <div className="flex items-center gap-2 w-full">
                    <Share2 className="w-4 h-4 text-primary" />
                    <span className="text-xs font-medium">Share with Doctor</span>
                    <ExternalLink className="w-3 h-3 ml-auto text-muted-foreground" />
                  </div>
                  <span className="text-[10px] text-muted-foreground">Secure email or portal</span>
                </Button>
              </div>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};